Better error handling
pantheon-systems/upstream-update-build pull request #4
Opened 2023-01-20 22:11 UTC by jazzsequence

This commit adds better error handling so that errors are not swallowed by piping output into other functions. It also removes the piped functions and the extra `set -x` since `set -ex ...` is already declared above (In line 58).

2023-01-20 22:13 UTC, greg-1-anderson requested changes
Let's put the `set -o pipefail` at the very top; there are some more `sed`s that could be removed too.

2023-01-20 22:17 UTC, greg-1-anderson requested changes
The script isn't going to work right if you put the `set -ex` at the top. Put just the `-o pipefail` at the top, and leave the `-ex` where it was.

2023-01-20 22:22 UTC, jazzsequence commented
@greg-1-anderson Okay to remove the `set -x` on line 79 though? (https://github.com/pantheon-systems/upstream-update-build/pull/4/files#diff-cbf8ba8e100970c2cf75029c927ce8366f1884db7e95e65a8b77a4a2f842e9d1L79) Or do we need that to be a different mode?

2023-01-21 01:09 UTC, greg-1-anderson approved these changes

2023-01-21 01:10 UTC, greg-1-anderson commented
Yep, we'll leave it in "echo" mode and "exit on failure" mode all the way until the end of the script. Test with invalid credentials to ensure that it's not echo-ing them when it fails at the end.

2023-01-23 16:38 UTC, jazzsequence commented
Merging. 
![butt holding](https://sfo2.digitaloceanspaces.com/cdn.jazzsequence/wp-content/uploads/sites/10/2021/10/15190335/52.gif)

2023-01-23 16:39 UTC, merged